{{- if .Values.rabbitmq.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Release.Name}}-rabbitmq-config-map"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
data:
  rabbitmq.conf: |-
    [default]
    hostname = {{ template "rabbitmq.host" . }}
    username = {{ .Values.rabbitmq.rabbitmq.username }}
    password = {{ .Values.rabbitmq.rabbitmq.password }}
  commands.txt: |-
    declare user name={{ .Values.rabbitmq.user.username }} password={{ .Values.rabbitmq.user.password }} tags=
    declare permission vhost=/ user={{ .Values.rabbitmq.user.username }} configure=.* read=.* write=.*
{{- end -}}
