language: java

env:
  global:
    - APPNAME="hyperspace"
    - ORG="fairspace"
    - ARTIFACT_BUILD_FILE=""
    - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
    - DEPLOYMENT_CONFIG_DIR="./ci-deployment"
    - RELEASE_BRANCH="master"
    - SNAPSHOT_BRANCH="dev"
    - GCP_PROJECT="fairspace-207108"
    - RELEASE_CONTEXT="FairspaceDemoCluster"
    - SNAPSHOT_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacecicluster"
    - RELEASE_CLUSTER_NAME="fairspacedemocluster"
    - SNAPSHOT_CLUSTER_NAME="fairspacecicluster"
    - RELEASE_CLUSTER_ZONE="europe-west1-b"
    - SNAPSHOT_CLUSTER_ZONE="europe-west1-b"
    - DOCKER_USERNAME="fairspace"
    - GITHUB_USERNAME="fairspace-ci"
    # Github credentials:
    # GITHUB_PASSWORD=....
    - secure: "JGk+4XeLruK1LMZ4zJcmX4k4T7nR7DVwPcl/IaPNKaR2+MdiN2Wi5gAXrsXDDKIs4fJzHtRBK1K+VNam4K8vwb5aOX0MnYDoHPZc3ye+UYUXLlTeoozSmfMy08zGaNtz+GjP+QSzvFcRMlhFRLjJ+Cae+Rwpt9gldSLhc04VPGBCMmnHAIg86m2PFqfEfm3Kjy7HkvrPYkAN8JvMRzSjXfBi0JmDjSFuXS0mcp/UOUZLtTzfASpaApijbkp2iposBfN83TbkmnZ/DbZULHtXcKB+mZWADRsh7vyIQQQLVkRWx3HcQSJKSEyCazYoINBufKXDek8v6EbPpIupwF8MVIZTL+vZKXteaNVkcad69ZD3iBhSje8M41ev1Q+m68z6+0IFm6xwajVPL02P3P64zaqWShrG8MLwNiZ7bYmZnziik+fKLGG0/ABiiTxVbUD4qW7XHzbdDNPSE4D9xTuKg+A2naydSNAdozKZLQUNK4/sk5S4xj5Ot0An3Jt9lHKMb/ayqn2b42MfvO3b6cW2pbJTd6f79z2O3bSjL0tNAWbkLrtQLnEPcr0d/CDPBnjWWk4N+1kcOaYqd6/KegkgxXCXSwDnbEhDp/GlEKiIvGo/F3JduqMnVZFfEK8IBIL0pm1z3T7Kvv2Fq5hE19TUB22dlExwudM1nDu8UUFjuig="

    # Azure credentials:
    - secure: "l8XP3jxyw7ufpMmwygEpVawwfuNFg2sEZirmENUVHRd3XLEuFUgIz4jGEY/nPeOfHCx7QL8sb41eR7dvZuZvT5OgdHwHFqxN5F79AGvzdKOFPn8MkmyhG1G2AwX44vHGOv1E6NQ06mKBKDoA/ieECnT6L+wxzQlM5PCl4+GJHniqlEnhQTwZO0o4yb/AdSBxMtCngx1mWAWDfmuTzg+IzOzkYbxTlf1M8jNfuiLc5qr3WS9qqGN2EddEoFaW+XANF8vk2g1ClZsjO/smGMEa84WCXSXziyYZ2R1F9uNyBm1NsTrbNggWnX7Ipu6KIN+1WXK6MmyMmiRnp03AO5N/FlmIGRMjFgrI3zO/O6uxnWTRep4cRPCARnfMrK+bgjRMI66HLuu2GWmF4GbXp/+8+Hu6zwIwa17+GMFVoOutB51tVS+WyyvnSkdLgc4X6o+aS1IDhvTd8g52UqQmMgjSmZ1quC8bM3ceLkTKcK+jkoHRg0o5z2LAfgs5koVDB+6TktDLdRi2TVefvMyYXTAIml+ws2ZqVxK/F9tFZFT3/GRMtbjbRthpwlt4GvnqMWQZloq6p8MuZ7HCSjU6p+ar9pVaX6tjDMhgQyLVIy92eE7aHa1IDpiqqUDwF2Cjs7+EnSOla+yUQh08d4F4z3VJay9ixdlS2pubuzvh9BLTRN0="

cache:
  directories:
  - $HOME/downloads

before_install:
  - export KUBE_CONFIG_ENC_KEY=$encrypted_985abdf32880_key
  - export KUBE_CONFIG_ENC_IV=$encrypted_985abdf32880_iv
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - 'if [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export ALLOW_SNAPSHOTS=1 DEPLOY_TARGET=ci KUBERNETES_CONTEXT="$SNAPSHOT_CONTEXT" DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$SNAPSHOT_CONTEXT" CLUSTER_NAME="$SNAPSHOT_CLUSTER_NAME" CLUSTER_ZONE="$SNAPSHOT_CLUSTER_ZONE"; fi'
  - 'if [[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_TARGET=demo KUBERNETES_CONTEXT="$RELEASE_CONTEXT" CLUSTER_NAME="$RELEASE_CLUSTER_NAME" CLUSTER_ZONE="$RELEASE_CLUSTER_ZONE"; fi'
  -  source ./ci/setup_env.sh

jobs:
  include:
    - stage: Build
      name: Helm chart
      install:
      - source charts/.travis/install.sh
      script:
      - ./ci/helm/tag.sh
      - ./ci/helm/add_repos.sh
      - ./ci/helm/build.sh
      - 'if [[ $SHOULD_RELEASE ]]; then ./ci/helm/release.sh && helm repo update; fi'
      - 'if [[ $SHOULD_RELEASE ]]; then travis_retry travis_wait ./ci/helm/deploy.sh $DEPLOY_TARGET; fi'
    - # For release branch, update git with the new tag and update version
      if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
      stage: Versioning
      install: skip
      name: Set tag and update version
      script:
        - ./ci/helm/tag.sh
        - ./ci/versioning/add_tag_to_git.sh
        - ./ci/versioning/set_next_version.sh

notifications:
  slack:
    rooms:
     - secure: "dpJL60bCwWHBbY23/6gTUWjLFo5FXp2+56k6EoxtFFwH7a8I9RAnuxHgbNknVypY115GgSpueSSbePaSlbGeHqZ/AQ1e6q2r80RQPBe+lFSc3+0DTkq00p97xqqFjpSSTE4+wYSGldP9GVpN89LLc9wZbSeI+GH3nr/vgMjTA8OPsUFPr49n/VNnqUm4I5SA2YKxYlVZuUoWGqWqj107LBiFFgOCUSeGgeM9wafFA86rxmkNU3h77g6N4rJrx8SUZrjFg158KHsN+nfnc6kFTHx+CJg+WSPx3T7Stf0XPPQe7pDgMpOucNH7n6duqa9V6ldhG9jati9BmSa74EzxzLGuhwVUiZgWQ0dZaND6hfTQnWk3/XKI9lNyUQ5uuCYuHaT33CiEiIt/HkigFoMgX6QkCPqk9eYAfVsOLz2nnqfmtT7AMM6xcCXrHRjJ7O/ZIo1UZaR5GwUD7j3JVA6UgNzztIBr+h/CyjvRSWQklOpVAYhCmuHJ1bEfKXfUx4Qkc0k5IaoefZ5uW5Ny64VBZoQMNt5MRxysKS9/ITqY4CALSxf0oBkQbxms5Oz967zFOWhD3+QL6sHAkLkVaUro1Y89Epm1YMqAaawC0DAFvrmeDXCITuPcDpsFHWVfpPLphxLA6d+TLZ5BNrdCpCj9GpDnFD0UkQ+wodZdfI6YaVo="
    template:
     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}"
     - "Latest commit: %{commit_message} - by %{author}"
     - "Result:  %{result} in %{duration}"
