dist: xenial

language: java

env:
  global:
    - NODE_VERSION="10.16.3"
    - APPNAME="hyperspace"
    - ORG="thehyve"
    - ARTIFACT_BUILD_FILE=""
    - BUILD_SCRIPTS_REPO="thehyve/fairspace-build-scripts"
    - DEPLOYMENT_CONFIG_REPO="thehyve/fairspace-config-private"
    - ACCOUNT_CONFIG_DIR="./.travis"
    - RELEASE_BRANCH="release"
    - SNAPSHOT_BRANCH="dev"
    - GCP_PROJECT="fairspace-207108"
    - SNAPSHOT_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacecicluster"
    - SNAPSHOT_CLUSTER_NAME="fairspacecicluster"
    - SNAPSHOT_CLUSTER_ZONE="europe-west1-b"
    - RELEASE_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacecicluster"
    - RELEASE_CLUSTER_NAME="fairspacecicluster"
    - RELEASE_CLUSTER_ZONE="europe-west1-b"
    - DOCKER_USERNAME="fairspace"
    - GITHUB_USERNAME="fairspace-ci"

    # DOCKER_PASSWORD=...
    - secure: "vXd6WTtZ5wO5hXi2Tm9lgSDWXkf8MyZ+zkSKr0DNXRqBFPPGpifzhB8qN1qRYVLD8UsdrFwU4q53kxqlmWd6/P9dQkFuFpkouZkax4LRoP7QhRbxcLUcbcqEui4pA579uAIynu61q+furr+4Yl6RcTTG6nE9T43eofgGQqf0haVRM9hYeeMXjHGBNPooHJepGxFqpMBSN/+nb3MoB9dOzqc+dvj99Z5BLiAnl5t9ZCHcqTaLlZpwhWY+vR5WyEj7D2mkAiswXmRCOB7n0z2dN/mxDvMLtXAM7pfmmpQUoZYI8bGUc2zBnzKb5slSvvVG4vgZKx0Tv8RDQnpj7geLmIoiWYfz4wGolp1kn4tvjIA5pSx/xXxpOAX/dVAM9hvtOYt48Unr76UzpQm1e3+2DYIZdf0jz5n9V3H2ZqYY81UWFI8nSTmvaO/dw3GtLiPts/+FAHPsXVAkUFmDf0AGrIXIQ7P31pLgtXwXMslr7HkDUDmdN3PMHn30QhJWsaFe+MWXKnqNjCgIfflHpmAVBkbjsKWG1wpsNUHB66rq3U9UPCXpxu1XVpJLxT5QfVXR8p10s4YBvhwHHqhBDbMETTCYz4Q5T7YwgWIU0JTwCut+OMmW4rR3IAwmgIF0Pnr64y+fZL+qNXSJp/W/wrN84ZoGFGBflSnaCIhK7dm+paA="

    # GITHUB_PASSWORD=....
    - secure: "dD7Fd1fyxJKMqN1aPjQPDlIYhSw8gMiKXFUImA013eAXaLmhGq7yc823evqpalx01+Ih8lrlE7Cg8NcXCcZw6RVaOAt44o3TbqrWOODnQ9epexEgB/yvbkmYoCfMY/cB3zfTOzNkUxMV4kHJ73MoC67bGKWyla+hdBu9iNLCVtPR38I87fj0CaSPmyaXEuOfEu/U0ADd6MeNEr1G+18rDze1LJt2fwORh+GXGa5ZdqTT0y/a0RvCIvfmmWMjhq0QOJubhjDlmK//r8hcRohz3R0NWi+8lxoytJa7A2MP2l4bFLZHDPFrbPFZ6IDgvG1Rh+ROOq8IDNVf1a8c0ct+fXwTTIwfQohq2k0Kl9BpUYdJVTR139N329QYQz1d8+WEjt9ywIdCJG0zDiZlOw/I12Tr9Rb+xVrFkDBCk/uEHzlhnSsq1H6WE/F5VDMi4GOhgxZyzV0Bk8Inl0sgHJO2QNVJyRZ6XKba5wcKAcxVxHWKXR/2WEQsdbgyCweXfAunYKFVWb7zHNv9w3Gt3Q99kE2HewscMiO5UfXGEAJgTOnKD7KpqE3NtB55R9Hk0qXCYs77DxV5BX41+K2lFMOaaWiJZaLl6QgrWTvhOSPGg/HqUpEdtEyqJpu0214cCYyIXev0Ouu5GP5EttZC055LpchBwh3mU+ccrZbxQs0ymx8="

cache:
  directories:
  - $HOME/downloads
  - $HOME/.gradle

before_install:
  - nvm install $NODE_VERSION
  - export KUBE_CONFIG_ENC_KEY=$encrypted_6c9f30024cb1_key
  - export KUBE_CONFIG_ENC_IV=$encrypted_6c9f30024cb1_iv
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - export BUILD_SCRIPTS_DIR=$(pwd)/ci
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$DEPLOYMENT_CONFIG_REPO ci-config
  - export DEPLOYMENT_CONFIG_DIR="$(pwd)/ci-config/fairspace-keycloak"
  - 'if [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export ALLOW_SNAPSHOTS=1 DEPLOY_TARGET=ci KUBERNETES_CONTEXT="$SNAPSHOT_CONTEXT" DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$SNAPSHOT_CONTEXT" CLUSTER_NAME="$SNAPSHOT_CLUSTER_NAME" CLUSTER_ZONE="$SNAPSHOT_CLUSTER_ZONE"; fi'
  - 'if [[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_TARGET=test KUBERNETES_CONTEXT="$RELEASE_CONTEXT" CLUSTER_NAME="$RELEASE_CLUSTER_NAME" DEPLOY_PLATFORM="GCP" CLUSTER_ZONE="$RELEASE_CLUSTER_ZONE"; fi'
  - source ./ci/setup_env.sh
  - 'if [[ "$SHOULD_RELEASE" ]] ; then export NEED_INTERNAL_HELM=1 ; fi'

jobs:
  include:
    - stage: build
      cache: false
      name: Build helm charts
      install:
        - source charts/.travis/install.sh
      script:
        - charts/.travis/build.sh
    - if: branch = release AND type != pull_request
      cache: false
      stage: Versioning
      name: Set tag and update version
      script:
        - "./ci/helm/tag.sh"
        - "ci/versioning/add_tag_to_git.sh"
        - "ci/versioning/set_next_version.sh"
    - stage: deploy
      cache: false
      if: branch = dev and type != pull_request
      install:
        - source charts/.travis/install.sh
      script:
        - travis_wait ci/helm/deploy.sh $DEPLOY_TARGET

notifications:
  slack:
    rooms:
     - secure: "dpJL60bCwWHBbY23/6gTUWjLFo5FXp2+56k6EoxtFFwH7a8I9RAnuxHgbNknVypY115GgSpueSSbePaSlbGeHqZ/AQ1e6q2r80RQPBe+lFSc3+0DTkq00p97xqqFjpSSTE4+wYSGldP9GVpN89LLc9wZbSeI+GH3nr/vgMjTA8OPsUFPr49n/VNnqUm4I5SA2YKxYlVZuUoWGqWqj107LBiFFgOCUSeGgeM9wafFA86rxmkNU3h77g6N4rJrx8SUZrjFg158KHsN+nfnc6kFTHx+CJg+WSPx3T7Stf0XPPQe7pDgMpOucNH7n6duqa9V6ldhG9jati9BmSa74EzxzLGuhwVUiZgWQ0dZaND6hfTQnWk3/XKI9lNyUQ5uuCYuHaT33CiEiIt/HkigFoMgX6QkCPqk9eYAfVsOLz2nnqfmtT7AMM6xcCXrHRjJ7O/ZIo1UZaR5GwUD7j3JVA6UgNzztIBr+h/CyjvRSWQklOpVAYhCmuHJ1bEfKXfUx4Qkc0k5IaoefZ5uW5Ny64VBZoQMNt5MRxysKS9/ITqY4CALSxf0oBkQbxms5Oz967zFOWhD3+QL6sHAkLkVaUro1Y89Epm1YMqAaawC0DAFvrmeDXCITuPcDpsFHWVfpPLphxLA6d+TLZ5BNrdCpCj9GpDnFD0UkQ+wodZdfI6YaVo="
    template:
     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}"
     - "Latest commit: %{commit_message} - by %{author}"
     - "Result:  %{result} in %{duration}"
