apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "frontend.fullname" . }}
  labels:
    app: frontend
    chart: {{ template "hyperspace.chart" . }}
    draft: {{ default "draft-app" .Values.draft }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: frontend
        release: {{ .Release.Name }}
{{- if .Values.podAnnotations.frontend }}
      annotations:
{{ toYaml .Values.podAnnotations.frontend | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ template "frontend.fullname" . }}
        image: "{{ .Values.frontend.image.image }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.internalPort }}
        volumeMounts:
          - name: config-storage
            mountPath: /usr/share/nginx/html/config/
        livenessProbe:
          httpGet:
            path: {{ .Values.frontend.probePath }}
            port: {{ .Values.frontend.service.internalPort }}
          initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.frontend.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.frontend.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.frontend.probePath }}
            port: {{ .Values.frontend.service.internalPort }}
          periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.frontend.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.frontend.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: config-storage
        configMap:
          name: {{ template "frontend.fullname" . }}
