apiVersion: v1
kind: Service
metadata:
  name: {{ template "frontend.fullname" . }}
  labels:
    app: frontend
    chart: {{ template "hyperspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.externalPort }}
    targetPort: {{ .Values.frontend.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: frontend
    release: {{ .Release.Name }}
