hyperspace:
  keycloak:
    realm: test
  ingress:
    domain: hyperspace.test.fairspace.app
    tls:
      certificate:
        dns01Provider: gke
  configurationScripts:
    dockerRepository: eu.gcr.io/fairspace-207108
    image: keycloak-configuration

# Set password to prevent having a new password at every upgrade
keycloak:
  keycloak:
    password: yJH7qVjAQ469MVNBR9L5
  postgresql:
    postgresPassword: "mf5-Y5Q5E5_P33eB"
