kind: Secret
apiVersion: v1
metadata:
  name: keycloak-postgresql
type: Opaque
data:
  password: {{ (.Values.fairspaceKeycloak.postgresql).postgresPassword | default (printf "%s-private" (include "fairspaceKeycloak.name" .)) | b64enc | quote }}
  postgres-password: {{ (.Values.fairspaceKeycloak.postgresql).postgresPassword | default (printf "%s-postgres-private" (include "fairspaceKeycloak.name" .)) | b64enc | quote }}
