apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logaggregator.fullname" . }}
  labels:
    app: portal
    chart: {{ template "hyperspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    rabbitmq:
      host: {{ template "rabbitmq.host" . }}
      username: {{ .Values.rabbitmq.user.username }}
      password: {{ .Values.rabbitmq.user.password }}