{{- if not .Values.logaggregator.persistence.logs.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: {{ template "hyperspace.fullname" . }}-logs
    labels:
        app: logaggregator
        chart: {{ template "hyperspace.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        {{- if .Values.logaggregator.persistence.logs.annotations }}
    annotations:
        {{ toYaml .Values.logaggregator.persistence.logs.annotations | indent 4 }}
        {{- end }}
spec:
    accessModes:
        - {{ .Values.logaggregator.persistence.logs.accessMode | quote }}
    resources:
        requests:
            storage: {{ .Values.logaggregator.persistence.logs.size | quote }}
        {{- if .Values.logaggregator.persistence.logs.storageClass }}
        {{- if (eq "-" .Values.logaggregator.persistence.logs.storageClass) }}
    storageClassName: ""
        {{- else }}
    storageClassName: "{{ .Values.logaggregator.persistence.logs.storageClass }}"
        {{- end }}
        {{- end }}
        {{- end -}}