apiVersion: v1
kind: Service
metadata:
  name: {{ template "logaggregator.fullname" . }}
  labels:
    app: logaggregator
    chart: {{ template "hyperspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.logaggregator.service.type }}
  ports: []
  selector:
    app: logaggregator
    release: {{ .Release.Name }}
