# Setup ingress for hyperspace components
hyperspace:
  name: Fairspace
  rbac:
    enabled: true
  ingress:
    enabled: true
    domain: keycloak.ci.fairway.app
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header  X-Forwarded-Proto \$scheme;
    tls:
      enabled: true
      secretNameOverride:
      certificate:
        obtain: true
        issuerRef:
          name: letsencrypt-prod
          kind: ClusterIssuer

  locationOverrides: { }

# Keycloak configuration
keycloak:
  enabled: true
  keycloak:
    username: keycloak
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false
    resources:
      requests:
        cpu: "10m"
        memory: "600Mi"
      limits:
        cpu: "500m"
        memory: "2048Mi"
  postgresql:
    persistence:
      enabled: true
    resources:
      # Request values are set by default in postgresql chart
      limits:
        cpu: "500m"
        memory: "512Mi"

# Generic settings for tracing
tracing:
  enabled: true
  samplingRate: 0.1
  baseUrl: http://jaeger-collector.jaeger:9411

podAnnotations: { }
