# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
fairspaceImagePullSecret:

# Setup ingress for hyperspace components
hyperspace:
    name: Fairspace
    keycloak:
        realm:
    ingress:
        enabled: true
        domain: hyperspace.ci.test.fairdev.app
        annotations:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: gke

    # Scripts for setting up keycloak for hyperspace
    configurationScripts:
        dockerRepository: eu.gcr.io
        image: fairspace-207108/keycloak-configuration
        configurationScriptsTag: 0.1.0
        pullPolicy: IfNotPresent
        resources:
            requests:
                cpu: "50m"
                memory: "512Mi"
            limits:
                cpu: "500m"
                memory: "2048Mi"
    organisationadmin:
        username:
        password: fairspace123
    locationOverrides: {}

# Keycloak configuration
keycloak:
    enabled: true
    keycloak:
        username: keycloak
        service:
            type: ClusterIP
            port: 80
        ingress:
            enabled: false
        resources:
            requests:
                cpu: "10m"
                memory: "600Mi"
            limits:
                cpu: "500m"
                memory: "2048Mi"
    postgresql:
        persistence:
            enabled: true
        resources:
            # Request values are set by default in postgresql chart
            limits:
                cpu: "500m"
                memory: "512Mi"

# Generic settings for tracing
tracing:
    enabled: true
    samplingRate: 0.1
    baseUrl: http://jaeger-collector.jaeger:9411

#####################################################################
# Specific settings for Pluto subchart
# Default configuration points to organisation portal
#####################################################################
pluto:
    replicaCount: 1
    rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    image:
        image: eu.gcr.io/fairspace-207108/pluto
        tag: 0.6.6
        pullPolicy: IfNotPresent
    service:
        type: ClusterIP
        externalPort: 80
        internalPort: 8080
    resources:
        limits:
            cpu: 1
            memory: 1024Mi
        requests:
            cpu: 50m
            memory: 300Mi
    probePath: /actuator/health
    livenessProbe:
        initialDelaySeconds: 20
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
    readinessProbe:
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
    terminationGracePeriodSeconds: 10

    # Keycloak configuration for authentication
    keycloak:
        client:
            id:
            secret:
        redirectAfterLogoutUrl:

    # Where to find the backends for this proxy
    backends:
        portal:

    # Zuul timeouts when connecting to upstream services
    socketTimeoutMillis: 15000
    connectTimeoutMillis: 2000

# Specific settings for Pluto subchart
# Default configuration points to organisation portal
#####################################################################
portal:
    replicaCount: 1
    rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    image:
        image: eu.gcr.io/fairspace-207108/portal
        tag: RELEASEVERSION
        pullPolicy: IfNotPresent
    service:
        type: ClusterIP
        externalPort: 80
        internalPort: 8080
    resources:
        limits:
            cpu: 1
            memory: 1024Mi
        requests:
            cpu: 50m
            memory: 300Mi
    probePath: /actuator/health
    livenessProbe:
        initialDelaySeconds: 20
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
    readinessProbe:
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
    terminationGracePeriodSeconds: 10

    # Keycloak configuration for authentication
    keycloak:
        client:
            id:
            secret:
        redirectAfterLogoutUrl:

    # Where to find the backends for this proxy
    backends:
        portal:

    # Zuul timeouts when connecting to upstream services
    socketTimeoutMillis: 15000
    connectTimeoutMillis: 2000

#####################################################################
# Specific settings for Frontend subchart
#####################################################################
frontend:
    replicaCount: 1
    image:
        image: eu.gcr.io/fairspace-207108/frontend
        tag: RELEASEVERSION
        pullPolicy: IfNotPresent
    service:
        type: ClusterIP
        externalPort: 80
        internalPort: 80
    resources:
        limits:
            cpu: 200m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 64Mi
    probePath: /
    livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
    readinessProbe:
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
    terminationGracePeriodSeconds: 10

podAnnotations: {}
