# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
fairspaceImagePullSecret:

# Setup ingress for hyperspace components
hyperspace:
    keycloak:
        realm:
    ingress:
        enabled: true
        domain: hyperspace.ci.test.fairdev.app
        annotations:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: gke
        controller:
            required: false

    # Scripts for setting up keycloak for hyperspace
    configurationScripts:
        dockerRepository: eu.gcr.io
        image: fairspace-207108/keycloak-configuration
        configurationScriptsTag: 0.1.0
        pullPolicy: IfNotPresent
        resources:
            requests:
                cpu: "50m"
                memory: "512Mi"
            limits:
                cpu: "500m"
                memory: "2048Mi"

# Keycloak configuration
keycloak:
    enabled: true
    keycloak:
        username: keycloak
        service:
            type: ClusterIP
            port: 80
        ingress:
            enabled: false
        resources:
            requests:
                cpu: "50m"
                memory: "1300Mi"
            limits:
                cpu: "500m"
                memory: "3612Mi"
    postgresql:
        persistence:
            enabled: true
        resources:
            # Request values are set by default in postgresql chart
            limits:
                cpu: "200m"
                memory: "1024Mi"
