# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
fairspaceImagePullSecret:

# Setup ingress for hyperspace components
hyperspace:
    name: Fairspace
    rbac:
        enabled: true
    keycloak:
        clientId: hyperspace
        clientSecret:
        realm:
    ingress:
        enabled: true
        domain: ci.test.fairdev.app
        annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/configuration-snippet: |
                proxy_set_header  X-Forwarded-Proto \$scheme;

        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer

    # Scripts for setting up keycloak for hyperspace
    configurationScripts:
        keycloak:
            dockerRepository: eu.gcr.io
            image: fairspace-207108/keycloak-configuration
            configurationScriptsTag: 0.1.5
            pullPolicy: IfNotPresent
            resources:
                requests:
                    cpu: "50m"
                    memory: "512Mi"
                limits:
                    cpu: "1"
                    memory: "2048Mi"
    organisationadmin:
        username:
        password: fairspace123
    testuser:
        generate: false
        password:
    locationOverrides: {}

# Keycloak configuration
keycloak:
    enabled: true
    keycloak:
        username: keycloak
        service:
            type: ClusterIP
            port: 80
        ingress:
            enabled: false
        resources:
            requests:
                cpu: "10m"
                memory: "600Mi"
            limits:
                cpu: "500m"
                memory: "2048Mi"
    postgresql:
        persistence:
            enabled: true
        resources:
            # Request values are set by default in postgresql chart
            limits:
                cpu: "500m"
                memory: "512Mi"

# Generic settings for tracing
tracing:
    enabled: true
    samplingRate: 0.1
    baseUrl: http://jaeger-collector.jaeger:9411

podAnnotations: {}
