# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
fairspaceImagePullSecret:

# Setup ingress for hyperspace components
hyperspace:
    keycloak:
        realm:
    ingress:
        enabled: true
        domain: hyperspace.ci.test.fairdev.app
        annotations:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: clouddns
        controller:
            required: false

    # Scripts for setting up keycloak for hyperspace
    configurationScripts:
        dockerRepository: fairspace.azurecr.io
        image: fairspace/keycloak-configuration
        configurationScriptsTag: 0.1.0
        pullPolicy: IfNotPresent

# Keycloak configuration
keycloak:
    enabled: true
    keycloak:
        username: keycloak
        service:
            type: ClusterIP
            port: 80
        ingress:
            enabled: false
    postgresql:
        persistence:
            enabled: true

