# Default values for helm-hyperspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

keycloak:
        keycloak:
                user: "keycloak"
                password: "1234567890"
                ingress:
                       enabled: true
                       path: /
                       hosts:
                         - keycloak.hyperspace.ci.test.fairdev.app
                       annotations:
                              kubernetes.io/ingress.class: nginx
                       tls:
                         - hosts:
                             - keycloak.hyperspace.ci.test.fairdev.app
                           secretName: hyperspace-ci-test-fairdev-app                       
        postgresql:
                postgresUser: "keycloakuser"
                postgresPassword: "123"

configurationScripts:
  dockerRepository: docker-registry.jx.test.fairdev.app
  image: fairspace/keycloak-configuration
  tag: 0.0.6
  pullPolicy: IfNotPresent

