replicaCount: 1
image:
    repository: docker-registry.jx.test.fairdev.app/fairspace/hyperspace
    tag: 0.1.52
    pullPolicy: IfNotPresent
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

# Setup ingress for hyperspace components
hyperspace:
    keycloak:
        realm:
    ingress:
        enabled: true
        domain: hyperspace.ci.test.fairdev.app
        annotations:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: clouddns
        controller:
            required: false

    # Scripts for setting up keycloak for hyperspace
    configurationScripts:
        dockerRepository: docker-registry.jx.test.fairdev.app
        image: fairspace/keycloak-configuration
        configurationScriptsTag: 0.0.23
        pullPolicy: IfNotPresent

# Keycloak configuration
keycloak:
    keycloak:
        username: keycloak
        service:
            type: ClusterIP
            port: 80
        ingress:
            enabled: false
    postgresql:
        persistence:
            enabled: true
