replicaCount: 1
image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
hyddperspace: null
keycloak:
    keycloak:
        service:
            type: NodePort
            port: 80
        ingress:
            enabled: true
            path: /
            hosts: 
                - keycloak.hyperspace.ci.test.fairdev.app
            annotations:
                kubernetes.io/ingress.class: nginx
            tls: 
                - hosts:
                    - keycloak.hyperspace.ci.test.fairdev.app
                  secretName: hyperspace-ci-test-fairdev-app
ingress.controller.required: true
