hyperspace:
  name: "Fairspace-CI"
  keycloak:
    clientSecret: e38026bd-c9d2-4430-8171-d3c58e8cec53
    realm: ci
  ingress:
    domain: hyperspace.ci.fairway.app
  configurationScripts:
    configurationScriptsTag: 0.1.4-SNAPSHOT
    pullPolicy: Always

# Set passwords to prevent having a new password at every upgrade
keycloak:
  keycloak:
      password: keycloak-ci-123
  postgresql:
    postgresPassword: "9FGwLKpEu$4w/knG"

pluto:
  image:
    tag: 0.6.7-SNAPSHOT
  keycloak:
    redirectAfterLogoutUrl:

portal:
  image:
    pullPolicy: Always

frontend:
  image:
    pullPolicy: Always