hyperspace:
  name: "ci"
  ingress:
    domain: ci.fairway.app
    tls:
      certificate:
        force: true
  configurationScripts:
    pullPolicy: Always

# Set passwords to prevent having a new password at every upgrade
keycloak:
  keycloak:
    password: keycloak-ci-123
  postgresql:
    postgresPassword: "9FGwLKpEu$4w/knG"
