hyperspace:
  name: "demo"
  keycloak:
    clientSecret: b91575e7-a61d-489d-8302-e25a29d794ed
    realm: demo
  ingress:
    domain: demo.fairway.app
  testuser:
    generate: true
    password: fairspace123

# Set password to prevent having a new password at every upgrade
keycloak:
  keycloak:
    password: keycloak-demo-123
  postgresql:
    postgresPassword: "mf5-Y5Q5E5_P33eB"

rabbitmq:
  rabbitmq:
    password: "gtzb28355LFqxbar"
    erlangCookie: "fLbZs6ncGzp9Q2R35V3zv9uQyDEjgyDy"
    diskFreeLimit: '"1GiB"'
  user:
    password: "z3fC4kPfysMEkYm2"
