auth:
  # Enables JWT/JWKS authentication. Defaults to false.
  enabled: false
  # JWKS URL
  jwksUrl: "https://keycloak.hyperspace.ci.fairway.app/auth/realms/ci/protocol/openid-connect/certs"
  # JWK encryption algorithm. Defaults to "RS256"
  jwtAlgorithm: RS256
charts:
  workspace: http://storage.googleapis.com/fairspace-helm/workspace-0.6.7-SNAPSHOT.tgz
