workspaces:
auth:
  enabled: false
  # JWKS URL
  jwksUrl: "https://keycloak.ci.fairway.app/auth/realms/ci/protocol/openid-connect/certs"
  # JWK encryption algorithm. Defaults to "RS256"
  algorithm: RS256


