apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pluto.fullname" . }}
  labels:
    app: pluto
    chart: {{ template "hyperspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    app:
      domains:
        - {{ template "hyperspace.url" . }}
      oauth2:
        base-url: {{ template "keycloak.baseUrl" . }}
        realm: {{ .Values.hyperspace.keycloak.realm }}
      apiVersion:
        pluto: v1
        portal: v1

    security:
      oidc:
        redirect-after-logout-url: {{ .Values.pluto.keycloak.redirectAfterLogoutUrl | default (include "hyperspace.url" .) }}
        required-authority: {{ .Values.hyperspace.organisationadmin.username | default (printf "orgnisation-admin-%s" (include "hyperspace.name" .)) }}
      urls:
        # Please note that by default pluto is configured to allow certain urls anonymously
        # (e.g. login or health), and is configured to require specific authorization for anything else
        # This configuration will make sure that all frontend resources can be accessed for anyone
        # that has logged in, even if the user does not have the required authority. This enables the
        # frontend to show a nice error message
        needsAuthentication:
        - /
        - /static/*
        - /public/*
        - /config/*
        - /workspaces/*
        - "*.js"
        - /api/${app.apiVersion.pluto}/account/*
    spring:
      zipkin:
        enabled: {{ .Values.tracing.enabled }}
        base-url: {{ .Values.tracing.baseUrl }}

    zuul:
      retryable: false
      host:
        connect-timeout-millis: {{ .Values.pluto.connectTimeoutMillis }}
        socket-timeout-millis: {{ .Values.pluto.socketTimeoutMillis }}
      routes:
        # Please note that the order of the routes is relevant
        portal:
          path: /api/${app.apiVersion.portal}/**
          url: {{ .Values.pluto.backends.portal | default (printf "http://%s-portal.%s.svc.cluster.local" .Release.Name .Release.Namespace)}}
          strip-prefix: false
        frontend:
          path: /**
          url: {{ .Values.pluto.backends.frontend | default (printf "http://%s-frontend.%s.svc.cluster.local" .Release.Name .Release.Namespace)}}
