apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    app: portal
    chart: {{ template "hyperspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    auth:
      jwksUrl: {{ template "keycloak.baseUrl" . }}/auth/realms/{{ .Values.hyperspace.keycloak.realm }}/protocol/openid-connect/certs
      jwtAlgorithm: RS256
      organisationAdminRole: organisation-admin-{{ .Values.hyperspace.name }}
    tiller:
      service: tiller-deploy.kube-system
      port: 44134
    charts:
      workspace: http://storage.googleapis.com/fairspace-helm/workspace-0.6.7-SNAPSHOT.tgz