apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    app: portal
    chart: {{ template "hyperspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    domain: {{ .Values.hyperspace.ingress.domain }}
    elasticSearchUrlTemplate: {{ .Release.Name }}-elasticsearch-client.{{ .Release.Namespace }}.svc.cluster.local/%s/_search
    auth:
      jwksUrl: {{ template "keycloak.baseUrl" . }}/auth/realms/{{ .Values.hyperspace.keycloak.realm }}/protocol/openid-connect/certs
      jwtAlgorithm: RS256
      organisationAdminRole: admin-organisation
    charts:
      workspace: http://storage.googleapis.com/fairspace-helm/workspace-0.6.7-SNAPSHOT.tgz
    workspace:
      hyperspace:
        keycloak:
          username: {{ .Values.keycloak.keycloak.username }}
          password: {{ .Values.keycloak.keycloak.password }}
          realm: {{ .Values.hyperspace.keycloak.realm }}
          clientSecret: {{ .Values.hyperspace.keycloak.clientSecret }}
        elasticsearch:
          transport:
            host: {{ .Release.Name }}-elasticsearch-discovery.{{ .Release.Namespace }}.svc.cluster.local
          rest:
            host: {{ .Release.Name }}-elasticsearch-client.{{ .Release.Namespace }}.svc.cluster.local
      saturn:
        mail:
{{ toYaml .Values.portal.mail | indent 10 }}
