apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    app: portal
    chart: {{ template "hyperspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    auth:
      enabled: true
      jwksUrl: {{ template "keycloak.baseUrl" . }}/auth/realms/{{ .Values.hyperspace.keycloak.realm }}/protocol/openid-connect/certs
      jwtAlgorithm: RS256
    charts:
      workspace: http://storage.googleapis.com/fairspace-helm/workspace-0.6.7-SNAPSHOT.tgz
    workspace:
      domainTemplate: workspace.%s.fairway.app
      config:
        hyperspace:
          domain: {{ .Values.hyperspace.ingress.domain .}}
          keycloak:
            username: {{ .Values.keycloak.keycloak.username .}}
            password: {{ .Values.keycloak.keycloak.password .}}
            realm: {{ .Values.hyperspace.keycloak.realm .}}
            clientSecret: {{ .Values.hyperspace.keycloak.clientSecret .}}
