apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    app: portal
    chart: {{ template "hyperspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    auth:
      jwksUrl: {{ template "keycloak.baseUrl" . }}/auth/realms/{{ .Values.hyperspace.keycloak.realm }}/protocol/openid-connect/certs
      jwtAlgorithm: RS256
      organisationAdminRole: {{ template "hyperspace.roles.organisation-admin" . }}
    charts:
      workspace: http://storage.googleapis.com/fairspace-helm/workspace-0.6.7-SNAPSHOT.tgz
