apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    app: portal
    chart: {{ template "hyperspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    domain: {{ .Values.hyperspace.ingress.domain }}
    elasticSearchUrlTemplate: http://{{ .Release.Name }}-elasticsearch-client.{{ .Release.Namespace }}.svc.cluster.local:9200/%s/_search
    auth:
      enabled: true
      jwksUrl: {{ template "keycloak.baseUrl" . }}/auth/realms/{{ .Values.hyperspace.keycloak.realm }}/protocol/openid-connect/certs
      jwtAlgorithm: RS256
      organisationAdminRole: organisation-admin
    charts:
      {{- range $key, $chartInfo := .Values.portal.charts }}
      {{ $key }}: {{ $chartInfo.repo }}{{ $chartInfo.file }}
      {{- end }}
    defaultConfig:
      workspace:
        hyperspace:
          keycloak:
            username: {{ .Values.keycloak.keycloak.username }}
            password: {{ .Values.keycloak.keycloak.password }}
            realm: {{ .Values.hyperspace.keycloak.realm }}
            clientSecret: {{ .Values.hyperspace.keycloak.clientSecret }}
          rabbitmq:
            enabled: {{ .Values.rabbitmq.enabled }}
            required: {{ .Values.rabbitmq.enabled }}
            host: {{ template "rabbitmq.host" . }}
            username: {{ .Values.rabbitmq.rabbitmq.username }}
            password: {{ .Values.rabbitmq.rabbitmq.password }}
          elasticsearch:
            transport:
              host: {{ .Release.Name }}-elasticsearch-discovery.{{ .Release.Namespace }}.svc.cluster.local
            rest:
              host: {{ .Release.Name }}-elasticsearch-client.{{ .Release.Namespace }}.svc.cluster.local
        saturn:
          mail:
{{ toYaml .Values.portal.mail | indent 12 }}
      jupyter:
        keycloak:
          baseUrl: {{ template "keycloak.baseUrl" . }}/auth
          username: {{ .Values.keycloak.keycloak.username }}
          password: {{ .Values.keycloak.keycloak.password }}
          realm: {{ .Values.hyperspace.keycloak.realm }}
        jupyterhub:
          rbac:
            enabled: true
          auth:
            custom:
              config:
                openid_url: {{ template "keycloak.baseUrl" . }}/auth/realms/{{ .Values.hyperspace.keycloak.realm }}/protocol/openid-connect/

