hyperspace:
  keycloak:
    realm: ci
  ingress:
    domain: hyperspace.ci.test.fairdev.app

# Set password to prevent having a new password at every upgrade
keycloak:
  keycloak:
      password: keycloak-ci-123