apiVersion: v2
appVersion: "1.0"
description: A Helm chart to install Keycloak
name: fairspace-keycloak
icon: https://raw.githubusercontent.com/thehyve/fairspace-keycloak/dev/charts/fairspace-keycloak/logo.jpg
version: 0.0.0-RELEASEVERSION

dependencies:
  - name: keycloakx
    version: 2.1.1
    repository: https://codecentric.github.io/helm-charts
