# Default values for fairspace-keycloak.

fairspaceKeycloak:
  name: fairspace-keycloak
  rbac:
    enabled: true
  locationOverrides: { }
  keycloak:
    username: keycloak
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false
    resources:
      requests:
        cpu: "10m"
        memory: "600Mi"
      limits:
        cpu: "500m"
        memory: "2048Mi"
  postgresql:
    persistence:
      enabled: true
    resources:
      # Request values are set by default in postgresql chart
      limits:
        cpu: "500m"
        memory: "512Mi"

ingress:
  enabled: true
  domain:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers: "256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header  X-Forwarded-Proto \$scheme;
  tls:
    enabled: true
    secretNameOverride:
    certificate:
      obtain: true
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer

# Generic settings for tracing
tracing:
  enabled: true
  samplingRate: 0.1
  baseUrl: http://jaeger-collector.jaeger:9411

# Pod annotations should remain empty. They are filled within the build process
podAnnotations: { }
