{{ if .Values.keycloak.enabled -}}
{{- $ingress := .Values.hyperspace.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "keycloak.prefix" . }}-ingress
{{- with $ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "hyperspace.name" . }}
    {{- include "hyperspace.labels" . | nindent 4 }}
spec:
{{- if $ingress.tls }}
  tls:
    - hosts:
      - {{ $ingress.domain }}
      secretName: {{ template "hyperspace.tlsSecretName" $ }}
{{- end }}
  rules:
    - host: {{ $ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "keycloak.prefix" . }}-http
              servicePort: http
{{- end -}}
{{ end -}}
