{{- $ingress := .Values.hyperspace.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "hyperspace.name" . }}-pluto-ingress
{{- with $ingress.annotations.pluto }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "hyperspace.name" . }}
    chart: {{ template "hyperspace.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
{{- if $ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ template "portal.hostname" $ }}
      secretName: {{ template "hyperspace.tlsSecretName" $ }}
{{- end }}
  rules:
    - host: {{ template "portal.hostname" $ }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "pluto.fullname" . }}
              servicePort: 80
{{- end -}}




