hyperspace:
  name: hyperspace-local
  ingress:
    domain: keycloak.local
    tls:
      enabled: false

# Set passwords to prevent having a new password at every upgrade
keycloak:
  postgresql:
    postgresPassword: "keycloak"
  extraEnv: |
    - name: KEYCLOAK_USER
      value: keycloak
    - name: KEYCLOAK_PASSWORD
      value: keycloak
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
